### ISSUE TITLE
DeOSS not uploading file to the miners that is already in the track directory.

### ISSUE THREAD

**Issue by tehsunnliu** [CESSProject/DeOSS#102]
Recently, I tried to upload a 1GiB file to my self-hosted DeOSS gateway. The gateway tried to upload the file segments to the miners for a while and then stopped. The file can not be found in the dealMap either. 
I can see that the file is still in the `/track` directory with FID: 34b9a4787bb567035f99add437938cbbf89087da4f8d6f9ba3844645349fcec0

![image](https://github.com/CESSProject/DeOSS/assets/15224865/e93296c3-22fa-4e4a-b5de-4b5da170c7b3)

When I restart the DeOSS, it resumes uploading other files but doesn't try to upload `34b9a4787bb567035f99add437938cbbf89087da4f8d6f9ba3844645349fcec0` this particular file.

**Comment by AstaFrode** [comment]
Please wait for the chain to reassign storage nodes.

**Comment by tehsunnliu** [comment]
Its actually 3rd Day today and the file is still there in track directory but isn't getting processed.

**Comment by AstaFrode** [comment]
The problem of slow speed is because the chain is stuck there, and the chain will not redistribute miners. CESS v0.7 version will solve this problem.
