### ISSUE TITLE
"rpc err: connection failed" While running a local DeOSS server.

### ISSUE THREAD

**Issue by tehsunnliu** [CESSProject/DeOSS#147]
Hi, we have our DeOSS gateway setup locally where we have our CESS rpc node running locally at `ws://localhost:9944/` on the same machine. 
Whenever we upload a file the DeOSS throws error 

```
[GIN] 2024/05/13 - 04:49:20 | 200 |  1.703779904s |   122.179.90.62 | PUT      "/"
XX 2024-05-13 04:49:21 [ws://localhost:9944/] rpc err: connection failed
XX 2024-05-13 04:49:21 rpc err: connection failed
XX 2024-05-13 04:49:31 [] rpc err: connection failed
++ 2024-05-13 04:49:32 [ws://localhost:9944/] rpc reconnection successful
```

<img width="698" alt="image" src="https://github.com/CESSProject/DeOSS/assets/15224865/b8130194-fd4c-4fc9-b7ca-b320b1f2cd87">

The DeOSS returns a file ID to the user however, the file doesn't get distributed to the miners, it can't be queried in CESS explorer
"fileBank > file" nor in "fileBank > dealmap".

The solution to the problem was to add some tokens to the DeOSS gateway wallet account address. Once enough token was added the file started showing up in deamap and also in the file upon successful distribution to the miners.

My concern is it will be helpful if a correct error message is reported by either DeOSS or the rpc "chain" logs stating that the DeOSS gateway doesn't have enough TCESS instead of RPC connection dropping every time. 

Looking forward for this to be fixed in the upcoming release.
Thank you.

**Comment by AstaFrode** [comment]
@tehsunnliu Will be fixed in the next version, current version: v0.3.6
