### ISSUE TITLE
Some function and  parameter naming seems abnormal

### ISSUE THREAD

**Issue by CheeringCharm** [CESSProject/DeOSS#178]
The naming of parameters and functions in the project code is not standardized. It is recommended to refer to: https://go.dev/doc/effective_go
It seems to me that one needs to use unified upper CamelCase?
![image](https://github.com/user-attachments/assets/960661a7-eb95-4377-b720-2fa96ad383e8)

**Comment by AstaFrode** [comment]
@CheeringCharm Fixed, thanks for your valuable feedback.
