### ISSUE TITLE
DeOSS looks like not support to upload huge file

### ISSUE THREAD

**Issue by democ98** [CESSProject/DeOSS#189]
When i use the function 'UploadFileChunks' in go-sdk try send file to Deoss,but always get 524 errorcode.Pls check the reason.

**Comment by AstaFrode** [comment]
@democ98 The 524 is limited due to cloudflare, please do not over rely on the public gateway and use it for your generation environment, we cannot guarantee the stability of the public gateway and recommend you run your own gateway.
